# Generated by Django 4.2.1 on 2023-05-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scribe_asset_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scribeassetmanager',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='scribeassetmanager',
            old_name='code',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='scribeassetmanager',
            name='language',
        ),
        migrations.RemoveField(
            model_name='scribeassetmanager',
            name='linenos',
        ),
        migrations.RemoveField(
            model_name='scribeassetmanager',
            name='style',
        ),
        migrations.AddField(
            model_name='scribeassetmanager',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
